apiVersion: v1
kind: Secret
metadata:
  name: test-secrets
  namespace: keda
data:
  AWS_ROLE_ARN: YXJuOmF3czppYW06OjYyMjI2ODEyNjU4Mjpyb2xlL2tlZGEtbmdpbnhkZW1vLXJvbGUtdGlnLTYzNTE= #arn:aws:iam::622268126582:role/keda-nginxdemo-role-tig-6351
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: sqs-trigger-auth-aws-role-arn
  namespace: keda
spec:
  secretTargetRef:
  - parameter: awsRoleArn    # The property in KEDA.
    name: test-secrets       # The name of the kubernetes secret.
    key: AWS_ROLE_ARN        # The key from the kubernetes secret.
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sqs-trigger-auth-aws-role-arn
spec:
  scaleTargetRef:
    name: nginx-deployment-pod-sa
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 10 
  cooldownPeriod:  10 
  triggers:
  - type: aws-sqs-queue
    metadata:
      queueURL: https://sqs.us-east-1.amazonaws.com/545444110299/keda_poc_queue
      activationQueueLength: "0"
      queueLength: "2"
      awsRegion: us-east-1
    authenticationRef:
      name: sqs-trigger-auth-aws-role-arn
