apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            # Use 'wget' to make an HTTP request to the target service
            wget -q -O /dev/null http://svc-nginx.keda.svc.cluster.local:80
            echo "Sent request to the target service"
            sleep 0.1  # Adjust the delay between requests as needed
          done