apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-check
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-check
  template:
    metadata:
      labels:
        app: network-check
    spec:
      containers:
      - name: busybox
        image: busybox:1.28
        command:
          - sleep
          - "3600"
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always