apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginxdemo-sqs-granual-access-sa
  namespace: keda
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::545444110299:role/keda-operator-sqs-granual-access-role-tig6351