apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc   # This should match the provisioner/storage class name for EBS
  resources:
    requests:
      storage: 8Gi   # Size of the volume
