apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  serviceName: "nginx-svc"
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: k8s.gcr.io/nginx-slim:0.8
          ports:
            - name: nginx-web
              containerPort: 80
          volumeMounts:
            - name: nginx-volumes-2
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-volumes-2
          persistentVolumeClaim:
            claimName: nginx-volumes-2
  volumeClaimTemplates:
    - metadata:
        name: nginx-volumes-2
      spec:
        storageClassName: "ebs-sc"
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 4Gi