kind: ConfigMap
apiVersion: v1
metadata:
  name: game-demo
  namespace: default
data:
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  #file -like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=10
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true