apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      env:
        # Define the environment variable
        - name: PLAYER_INITIAL_LIVES # Notice that the case is different here
                                     # from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: game-demo           # The ConfigMap this value comes from.
              key: player_initial_lives # The key to fetch.
        - name: ENEMY_TYPES
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: game.properties
              subPath: enemy.types
        - name: ENEMY_TYPES
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: game.properties
      volumeMounts:
      - name: config
        mountPath: "/config/properties"
        readOnly: true
  volumes:
  # You set volumes at the Pod level, then mount them into containers inside that Pod
  - name: config
    configMap:
      # Provide the name of the ConfigMap you want to mount.
      name: game-demo
        