apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: addon-manager
rules:
- apiGroups: [""]
  resources: ["addons"]
  verbs: ["create", "update", "delete", "get", "list", "watch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-masters-addon-manager-cluster-role-binding
subjects:
- kind: Group
  name: system:masters
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: addon-manager
  apiGroup: rbac.authorization.k8s.io

