
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-service-account
  namespace: default  # Specify the namespace where you want to create the ServiceAccount

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-sa-sample
  annotations:
    kubernetes.io/service-account.name: "example-service-account"
type: kubernetes.io/service-account-token
data:
  extra: YmFyCg==

